// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/**
 * OsherMonitor.sol
 * ─────────────────────────────────────────────────────────────────
 * Deployed on: Celo Mainnet (chainId 42220)
 *
 * What it does:
 *   1. Called by orchestrator.js BEFORE executing any bridge transfer.
 *   2. Collects a basis-point service fee from the transfer amount.
 *   3. Emits a structured event for every transaction (off-chain indexing).
 *   4. Owner can update fee rate and withdraw collected fees.
 *
 * Fee model:
 *   - Fee is taken in the ERC-20 token being transferred (USDC/USDT/USDm/CELO).
 *   - feeBps = 50 by default = 0.5% (matches SERVICE_FEE_PERCENT in keys.js).
 *   - Max fee cap: 500 bps = 5% (hard-coded safety ceiling).
 *
 * Ownership:
 *   - Single owner at deploy time.
 *   - transferOwnership() available for future multisig migration.
 *
 * Upgradeability:
 *   - Intentionally NOT upgradeable (immutable logic, per your requirement).
 *   - Deploy a new contract and call setSuccessor() to migrate gracefully.
 * ─────────────────────────────────────────────────────────────────
 */

interface IERC20 {
    function transferFrom(address sender, address recipient, uint256 amount) external returns (bool);
    function transfer(address recipient, uint256 amount) external returns (bool);
    function balanceOf(address account) external view returns (uint256);
    function decimals() external view returns (uint8);
}

contract OsherMonitor {

    // ── State ──────────────────────────────────────────────────────

    address public owner;
    address public feeVault;       // Where collected fees are held (this contract)
    address public successor;      // Next contract address when migrating

    uint16  public feeBps;         // Fee in basis points (50 = 0.5%)
    uint16  public constant MAX_FEE_BPS = 500; // Hard ceiling: 5%

    bool    public paused;         // Emergency pause

    // Cumulative stats (gas-cheap uint128)
    uint128 public totalTransactions;
    uint128 public totalVolumeUSD;  // Approximate, scaled by 1e6 (6 decimals)

    // ── Supported tokens ──────────────────────────────────────────
    // Only whitelisted tokens can use this contract.
    // Prevents fee drain via unknown/malicious tokens.
    mapping(address => bool)   public supportedTokens;
    mapping(address => string) public tokenSymbols;

    // Fee balances per token accumulated in this contract
    mapping(address => uint256) public collectedFees;

    // ── Events ────────────────────────────────────────────────────

    /**
     * Emitted on every bridge transfer routed through Osher AI.
     * Off-chain indexers (The Graph, custom listener) subscribe to this.
     */
    event TransferLogged(
        bytes32 indexed txId,        // Unique ID generated by orchestrator
        address indexed sender,      // Agent wallet (from keys.js AGENT_WALLET_ADDRESS)
        address indexed token,       // ERC-20 token address
        string  tokenSymbol,         // Human-readable: "USDC", "USDT", "USDm", "CELO"
        uint256 amount,              // Transfer amount (token decimals)
        uint256 feeCharged,          // Fee taken (token decimals)
        string  fromChain,           // Always "celo" for this contract
        string  toChain,             // "base", "ethereum", "polygon", "arbitrum", "solana"
        string  bridge,              // "Axelar", "Wormhole", "LayerZero", "Celer"
        string  toAddress,           // Destination address (string for cross-chain compat)
        uint256 timestamp
    );

    /**
     * Emitted on every on-chain swap (USDm → USDC etc. via Mento)
     */
    event SwapLogged(
        bytes32 indexed txId,
        address indexed sender,
        address indexed fromToken,
        address toToken,
        uint256 fromAmount,
        uint256 toAmount,
        uint256 feeCharged,
        string  protocol,            // "mento", "uniswap"
        uint256 timestamp
    );

    event FeeUpdated(uint16 oldBps, uint16 newBps);
    event FeeWithdrawn(address indexed token, address indexed to, uint256 amount);
    event TokenAdded(address indexed token, string symbol);
    event TokenRemoved(address indexed token);
    event OwnershipTransferred(address indexed oldOwner, address indexed newOwner);
    event Paused(address indexed by);
    event Unpaused(address indexed by);
    event SuccessorSet(address indexed successor);

    // ── Modifiers ────────────────────────────────────────────────

    modifier onlyOwner() {
        require(msg.sender == owner, "OsherMonitor: not owner");
        _;
    }

    modifier notPaused() {
        require(!paused, "OsherMonitor: contract is paused");
        _;
    }

    modifier onlySupported(address token) {
        require(supportedTokens[token], "OsherMonitor: token not supported");
        _;
    }

    // ── Constructor ──────────────────────────────────────────────

    /**
     * @param _owner         Your deployer wallet (becomes admin)
     * @param _feeBps        Initial fee in basis points (50 = 0.5%)
     * @param _initialTokens Token addresses to whitelist at deploy time
     * @param _tokenSymbols  Human-readable symbols matching _initialTokens
     */
    constructor(
        address _owner,
        uint16  _feeBps,
        address[] memory _initialTokens,
        string[]  memory _tokenSymbols
    ) {
        require(_owner != address(0),       "OsherMonitor: zero owner");
        require(_feeBps <= MAX_FEE_BPS,     "OsherMonitor: fee exceeds max");
        require(_initialTokens.length == _tokenSymbols.length, "OsherMonitor: array mismatch");

        owner    = _owner;
        feeVault = address(this);  // Fees stay in this contract until withdrawn
        feeBps   = _feeBps;

        for (uint256 i = 0; i < _initialTokens.length; i++) {
            require(_initialTokens[i] != address(0), "OsherMonitor: zero token address");
            supportedTokens[_initialTokens[i]] = true;
            tokenSymbols[_initialTokens[i]]    = _tokenSymbols[i];
            emit TokenAdded(_initialTokens[i], _tokenSymbols[i]);
        }
    }

    // ── Core: Log + Collect Fee ───────────────────────────────────

    /**
     * recordTransfer()
     * ─────────────────────────────────────────────────────────────
     * Called by orchestrator.js BEFORE submitting the bridge tx.
     *
     * Flow:
     *   1. Pulls `feeAmount` from msg.sender into this contract.
     *   2. Emits TransferLogged event.
     *   3. Returns the actual fee charged (for orchestrator to record).
     *
     * The orchestrator must have approved this contract to spend
     * `feeAmount` of `token` before calling this function.
     *
     * @param txId       Unique ID — use ethers.id(sessionId + timestamp)
     * @param token      ERC-20 token address being transferred
     * @param amount     Full transfer amount (in token's native decimals)
     * @param toChain    Destination chain name string
     * @param bridge     Bridge name string
     * @param toAddress  Destination wallet address (as string)
     */
    function recordTransfer(
        bytes32       txId,
        address       token,
        uint256       amount,
        string calldata toChain,
        string calldata bridge,
        string calldata toAddress
    )
        external
        notPaused
        onlySupported(token)
        returns (uint256 feeCharged)
    {
        require(amount > 0,           "OsherMonitor: zero amount");
        require(bytes(toChain).length > 0,   "OsherMonitor: empty toChain");
        require(bytes(toAddress).length > 0, "OsherMonitor: empty toAddress");

        // Calculate fee
        feeCharged = (amount * feeBps) / 10_000;

        // Pull fee from caller into this contract
        if (feeCharged > 0) {
            bool ok = IERC20(token).transferFrom(msg.sender, address(this), feeCharged);
            require(ok, "OsherMonitor: fee transfer failed");
            collectedFees[token] += feeCharged;
        }

        // Update stats
        unchecked {
            totalTransactions += 1;
            // Approximate USD volume (assumes 6-decimal stablecoins)
            totalVolumeUSD += uint128(amount);
        }

        emit TransferLogged(
            txId,
            msg.sender,
            token,
            tokenSymbols[token],
            amount,
            feeCharged,
            "celo",
            toChain,
            bridge,
            toAddress,
            block.timestamp
        );

        return feeCharged;
    }

    /**
     * recordSwap()
     * ─────────────────────────────────────────────────────────────
     * Called by orchestrator.js when a swap (USDm→USDC etc.) happens.
     * Collects fee on the input token.
     *
     * @param txId        Unique ID
     * @param fromToken   Input token address
     * @param toToken     Output token address
     * @param fromAmount  Input amount
     * @param toAmount    Output amount (after swap, for logging)
     * @param protocol    "mento" or "uniswap"
     */
    function recordSwap(
        bytes32         txId,
        address         fromToken,
        address         toToken,
        uint256         fromAmount,
        uint256         toAmount,
        string calldata protocol
    )
        external
        notPaused
        onlySupported(fromToken)
        returns (uint256 feeCharged)
    {
        require(fromAmount > 0, "OsherMonitor: zero amount");

        feeCharged = (fromAmount * feeBps) / 10_000;

        if (feeCharged > 0) {
            bool ok = IERC20(fromToken).transferFrom(msg.sender, address(this), feeCharged);
            require(ok, "OsherMonitor: fee transfer failed");
            collectedFees[fromToken] += feeCharged;
        }

        unchecked { totalTransactions += 1; }

        emit SwapLogged(
            txId,
            msg.sender,
            fromToken,
            toToken,
            fromAmount,
            toAmount,
            feeCharged,
            protocol,
            block.timestamp
        );

        return feeCharged;
    }

    // ── Owner: Fee Management ────────────────────────────────────

    /**
     * Withdraw all collected fees for a given token to a recipient.
     * Only callable by owner.
     */
    function withdrawFees(address token, address to) external onlyOwner {
        require(to != address(0), "OsherMonitor: zero recipient");
        uint256 balance = collectedFees[token];
        require(balance > 0, "OsherMonitor: no fees to withdraw");

        collectedFees[token] = 0;
        bool ok = IERC20(token).transfer(to, balance);
        require(ok, "OsherMonitor: withdrawal failed");

        emit FeeWithdrawn(token, to, balance);
    }

    /**
     * Withdraw all fees for multiple tokens in one call.
     */
    function withdrawAllFees(address[] calldata tokens, address to) external onlyOwner {
        require(to != address(0), "OsherMonitor: zero recipient");
        for (uint256 i = 0; i < tokens.length; i++) {
            uint256 balance = collectedFees[tokens[i]];
            if (balance == 0) continue;
            collectedFees[tokens[i]] = 0;
            IERC20(tokens[i]).transfer(to, balance);
            emit FeeWithdrawn(tokens[i], to, balance);
        }
    }

    // ── Owner: Config ─────────────────────────────────────────────

    function setFeeBps(uint16 newBps) external onlyOwner {
        require(newBps <= MAX_FEE_BPS, "OsherMonitor: exceeds max fee");
        emit FeeUpdated(feeBps, newBps);
        feeBps = newBps;
    }

    function addToken(address token, string calldata symbol) external onlyOwner {
        require(token != address(0),    "OsherMonitor: zero address");
        require(bytes(symbol).length > 0, "OsherMonitor: empty symbol");
        supportedTokens[token] = true;
        tokenSymbols[token]    = symbol;
        emit TokenAdded(token, symbol);
    }

    function removeToken(address token) external onlyOwner {
        supportedTokens[token] = false;
        emit TokenRemoved(token);
    }

    function setPaused(bool _paused) external onlyOwner {
        paused = _paused;
        if (_paused) emit Paused(msg.sender);
        else         emit Unpaused(msg.sender);
    }

    function transferOwnership(address newOwner) external onlyOwner {
        require(newOwner != address(0), "OsherMonitor: zero address");
        emit OwnershipTransferred(owner, newOwner);
        owner = newOwner;
    }

    /**
     * Point to next contract version for graceful migration.
     * Frontend/backend can read this to know if a new contract is live.
     */
    function setSuccessor(address _successor) external onlyOwner {
        successor = _successor;
        emit SuccessorSet(_successor);
    }

    // ── Views ────────────────────────────────────────────────────

    function getCollectedFee(address token) external view returns (uint256) {
        return collectedFees[token];
    }

    function calculateFee(uint256 amount) external view returns (uint256) {
        return (amount * feeBps) / 10_000;
    }

    function isTokenSupported(address token) external view returns (bool) {
        return supportedTokens[token];
    }

    /**
     * Returns contract summary for admin dashboard / health check.
     */
    function getStats() external view returns (
        uint128 txCount,
        uint128 volumeUSD,
        uint16  currentFeeBps,
        bool    isPaused,
        address currentOwner,
        address nextContract
    ) {
        return (
            totalTransactions,
            totalVolumeUSD,
            feeBps,
            paused,
            owner,
            successor
        );
    }

    // Reject accidental ETH/CELO sends
    receive() external payable { revert("OsherMonitor: no native token accepted"); }
    fallback() external payable { revert("OsherMonitor: no native token accepted"); }
}
