[package]
name = "osher_monitor"
version = "0.1.0"
description = "Osher AI transaction monitor and fee collector for Solana"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "osher_monitor"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang  = "0.29.0"
anchor-spl   = "0.29.0"
